### ISSUE TITLE
acr1281s support

### ISSUE THREAD

**Issue by stsp** [acshk/acsccid#13]
Hi.

Are there any support for acr1281s reader?
This project lists acr1281U - presumably an USB
version of the same reader, but mine is rs-232.
Are there any plans to support that, or how difficult
would it be for me to change the usb version to
use serial port?

**Comment by godfreychung** [comment]
Sorry, current version does not support ACR1281S.

Normally, it depends on the number of requests and the type of project. Otherwise, it will depend on my free time.

Actually, serial port access and CCID protocol implementation can be borrowed from ccid. You need to implement the serial protocol as well as handling retries and timeout.
